/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment03_f2019027065;

import com.sun.jndi.cosnaming.CNCtx;
import java.awt.Color;

/**
 *
 * @author Aslam Javed
 */
public class patientRegister extends javax.swing.JFrame {

    /**
     * Creates new form patientRegister
     */
    public patientRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelone = new javax.swing.JPanel();
        titlelabel = new javax.swing.JLabel();
        paneltwo = new javax.swing.JPanel();
        typelabel = new javax.swing.JLabel();
        labeltitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cniclabel = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();
        titlecombobox = new javax.swing.JComboBox<>();
        agetxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        fullnamelabel = new javax.swing.JLabel();
        companylabel1 = new javax.swing.JLabel();
        contactpersonlabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        companytxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        persontxt = new javax.swing.JTextField();
        mrlabel = new javax.swing.JLabel();
        NUMFIELD = new javax.swing.JTextField();
        fullabel = new javax.swing.JTextField();
        fullabelone = new javax.swing.JTextField();
        genderlabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        maritallabel = new javax.swing.JLabel();
        statusbox = new javax.swing.JComboBox<>();
        relationlabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        dobtxt = new javax.swing.JFormattedTextField();
        cnictxt = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        tehsillabel = new javax.swing.JLabel();
        Addresslabel = new javax.swing.JLabel();
        tehsiltxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        panelthree = new javax.swing.JPanel();
        mobilelabel = new javax.swing.JLabel();
        otherlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        mobiletxt = new javax.swing.JTextField();
        othertxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        panelfour = new javax.swing.JPanel();
        activecheckbox = new javax.swing.JCheckBox();
        diedcheckbox = new javax.swing.JCheckBox();
        govtempcheckbox = new javax.swing.JCheckBox();
        confidentialcheckbox = new javax.swing.JCheckBox();
        printcardbtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        Attachpicbtn = new javax.swing.JButton();
        neewbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        panelfive = new javax.swing.JPanel();
        orderbutton = new javax.swing.JButton();
        orderbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelone.setForeground(new java.awt.Color(51, 153, 255));

        titlelabel.setBackground(new java.awt.Color(51, 102, 255));
        titlelabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titlelabel.setForeground(new java.awt.Color(51, 102, 255));
        titlelabel.setText("Patient Registration");
        titlelabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titlelabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                titlelabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout paneloneLayout = new javax.swing.GroupLayout(panelone);
        panelone.setLayout(paneloneLayout);
        paneloneLayout.setHorizontalGroup(
            paneloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneloneLayout.setVerticalGroup(
            paneloneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        paneltwo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        typelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typelabel.setText("Type");

        labeltitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltitle.setText("Title");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Age");

        cniclabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cniclabel.setText("CNIC");

        typetxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typetxt.setForeground(new java.awt.Color(204, 204, 204));
        typetxt.setText("Ctrl + F9 to LOV");
        typetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        typetxt.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });

        titlecombobox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titlecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Miss.", "Mrs." }));
        titlecombobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agetxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year(s)" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fullnamelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fullnamelabel.setText("Full Name");

        companylabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        companylabel1.setText("Company");

        contactpersonlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contactpersonlabel.setText("Contact Person");

        doblabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doblabel.setText("D.O.B");

        companytxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        companytxt.setForeground(new java.awt.Color(204, 204, 204));
        companytxt.setText("Ctrl + F9 to LOV");
        companytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companytxtActionPerformed(evt);
            }
        });

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nametxt.setForeground(new java.awt.Color(204, 204, 204));
        nametxt.setText("Hint: MUHAMMAD");

        persontxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        persontxt.setForeground(new java.awt.Color(204, 204, 204));
        persontxt.setText("Hint: Ali");

        mrlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mrlabel.setText("Mr num");

        fullabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullabel.setForeground(new java.awt.Color(204, 204, 204));
        fullabel.setText("ANWAR");

        fullabelone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullabelone.setForeground(new java.awt.Color(204, 204, 204));
        fullabelone.setText("ALI");

        genderlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderlabel.setText("Gender");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        maritallabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maritallabel.setText("Marital Status");

        statusbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statusbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widow", "widower" }));

        relationlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        relationlabel.setText("Relation");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Ctrl + F9 to LOV");

        cnictxt.setText("     -      -");

        javax.swing.GroupLayout paneltwoLayout = new javax.swing.GroupLayout(paneltwo);
        paneltwo.setLayout(paneltwoLayout);
        paneltwoLayout.setHorizontalGroup(
            paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(typelabel)
                        .addGap(18, 18, 18)
                        .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cniclabel))
                        .addGap(18, 18, 18)
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneltwoLayout.createSequentialGroup()
                                .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cnictxt)))
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(labeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titlecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(companylabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(fullnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(doblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobtxt))
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(contactpersonlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(persontxt)))
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneltwoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(fullabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fullabelone))
                            .addGroup(paneltwoLayout.createSequentialGroup()
                                .addComponent(mrlabel)
                                .addGap(18, 18, 18)
                                .addComponent(NUMFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(paneltwoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderlabel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maritallabel)
                                .addGap(18, 18, 18)
                                .addComponent(statusbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(relationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paneltwoLayout.setVerticalGroup(
            paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltwoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companylabel1)
                    .addComponent(companytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrlabel)
                    .addComponent(NUMFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titlecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labeltitle)
                        .addComponent(fullnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fullabelone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(doblabel))
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2)
                            .addComponent(maritallabel)
                            .addComponent(genderlabel)
                            .addComponent(statusbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addComponent(dobtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cniclabel)
                            .addComponent(contactpersonlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(paneltwoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(paneltwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(persontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tehsillabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tehsillabel.setText("Tehsil");

        Addresslabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addresslabel.setText("Address");

        tehsiltxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tehsiltxt.setForeground(new java.awt.Color(204, 204, 204));
        tehsiltxt.setText("Ctrl + F9 to LOV");

        addresstxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addresstxt.setForeground(new java.awt.Color(204, 204, 204));
        addresstxt.setText("Hint: Permanent Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tehsillabel)
                .addGap(18, 18, 18)
                .addComponent(tehsiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Addresslabel)
                .addGap(18, 18, 18)
                .addComponent(addresstxt)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Addresslabel))
                            .addComponent(tehsillabel))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tehsiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
            .addComponent(addresstxt, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelthree.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mobilelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobilelabel.setText("Mobile");

        otherlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        otherlabel.setText("Other");

        emaillabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emaillabel.setText("Email");

        mobiletxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mobiletxt.setForeground(new java.awt.Color(204, 204, 204));
        mobiletxt.setText("Hint: 03000111111111");

        othertxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        othertxt.setForeground(new java.awt.Color(204, 204, 204));
        othertxt.setText("Hint: 042934847765");

        emailtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(204, 204, 204));
        emailtxt.setText("Hint: anwar@gamil.com");

        javax.swing.GroupLayout panelthreeLayout = new javax.swing.GroupLayout(panelthree);
        panelthree.setLayout(panelthreeLayout);
        panelthreeLayout.setHorizontalGroup(
            panelthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelthreeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mobilelabel)
                .addGap(27, 27, 27)
                .addComponent(mobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(otherlabel)
                .addGap(18, 18, 18)
                .addComponent(othertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emaillabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailtxt)
                .addContainerGap())
        );
        panelthreeLayout.setVerticalGroup(
            panelthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelthreeLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilelabel)
                    .addComponent(otherlabel)
                    .addComponent(emaillabel))
                .addGap(19, 19, 19))
            .addGroup(panelthreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelthreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailtxt)
                    .addComponent(othertxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mobiletxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        panelfour.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        activecheckbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        activecheckbox.setText("Active");

        diedcheckbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diedcheckbox.setText("Died");

        govtempcheckbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        govtempcheckbox.setText("Govt Employee");

        confidentialcheckbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confidentialcheckbox.setText("Confidential");

        printcardbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printcardbtn.setText("Print Card");

        reportbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportbtn.setText("Reports");

        Attachpicbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Attachpicbtn.setText("Attach Picture");

        neewbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        neewbtn.setText("New");

        editbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editbtn.setText("Edit");

        javax.swing.GroupLayout panelfourLayout = new javax.swing.GroupLayout(panelfour);
        panelfour.setLayout(panelfourLayout);
        panelfourLayout.setHorizontalGroup(
            panelfourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfourLayout.createSequentialGroup()
                        .addComponent(activecheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(govtempcheckbox))
                    .addGroup(panelfourLayout.createSequentialGroup()
                        .addComponent(diedcheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confidentialcheckbox)))
                .addGap(53, 53, 53)
                .addComponent(reportbtn)
                .addGap(62, 62, 62)
                .addComponent(printcardbtn)
                .addGap(62, 62, 62)
                .addComponent(Attachpicbtn)
                .addGap(71, 71, 71)
                .addComponent(neewbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editbtn)
                .addGap(50, 50, 50))
        );
        panelfourLayout.setVerticalGroup(
            panelfourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activecheckbox)
                    .addComponent(govtempcheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelfourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diedcheckbox)
                    .addComponent(confidentialcheckbox))
                .addContainerGap())
            .addGroup(panelfourLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelfourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportbtn)
                    .addComponent(printcardbtn)
                    .addComponent(Attachpicbtn)
                    .addComponent(neewbtn)
                    .addComponent(editbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelfive.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        orderbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment03_f2019027065/cart-icon.png"))); // NOI18N
        orderbutton.setText("Order");

        orderbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderbtn.setText("ORDER");

        javax.swing.GroupLayout panelfiveLayout = new javax.swing.GroupLayout(panelfive);
        panelfive.setLayout(panelfiveLayout);
        panelfiveLayout.setHorizontalGroup(
            panelfiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfiveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        panelfiveLayout.setVerticalGroup(
            panelfiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfiveLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelfiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneltwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelthree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelfour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelfive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneltwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelthree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelfour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelfive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titlelabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_titlelabelAncestorAdded
               
        //titlelabel.setBackground(Color.BLUE);
    }//GEN-LAST:event_titlelabelAncestorAdded

    private void companytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companytxtActionPerformed

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        typetxt type = new typetxt();
       // type.setPlaceholder("Ctrl + L or F9 to LOV");
    }//GEN-LAST:event_typetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addresslabel;
    private javax.swing.JButton Attachpicbtn;
    private javax.swing.JTextField NUMFIELD;
    private javax.swing.JCheckBox activecheckbox;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel cniclabel;
    private javax.swing.JFormattedTextField cnictxt;
    private javax.swing.JLabel companylabel1;
    private javax.swing.JTextField companytxt;
    private javax.swing.JCheckBox confidentialcheckbox;
    private javax.swing.JLabel contactpersonlabel;
    private javax.swing.JCheckBox diedcheckbox;
    private javax.swing.JLabel doblabel;
    private javax.swing.JFormattedTextField dobtxt;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fullabel;
    private javax.swing.JTextField fullabelone;
    private javax.swing.JLabel fullnamelabel;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JCheckBox govtempcheckbox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labeltitle;
    private javax.swing.JLabel maritallabel;
    private javax.swing.JLabel mobilelabel;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JLabel mrlabel;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton neewbtn;
    private javax.swing.JButton orderbtn;
    private javax.swing.JButton orderbutton;
    private javax.swing.JLabel otherlabel;
    private javax.swing.JTextField othertxt;
    private javax.swing.JPanel panelfive;
    private javax.swing.JPanel panelfour;
    private javax.swing.JPanel panelone;
    private javax.swing.JPanel panelthree;
    private javax.swing.JPanel paneltwo;
    private javax.swing.JTextField persontxt;
    private javax.swing.JButton printcardbtn;
    private javax.swing.JLabel relationlabel;
    private javax.swing.JButton reportbtn;
    private javax.swing.JComboBox<String> statusbox;
    private javax.swing.JLabel tehsillabel;
    private javax.swing.JTextField tehsiltxt;
    private javax.swing.JComboBox<String> titlecombobox;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JLabel typelabel;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables

    private static class cnictxt {

        public cnictxt() {
        }
    }

    private static class typetxt {

        public typetxt() {
        }
    }
}
